import {useEffect,useState} from 'react';
import {api,boundaryAnchor,label,pillarLabels,preferences,type Choice,type Criterion,type Place,type Profile} from './domain';
import {MapView} from './Map';
const five=['health','transportation','quality_of_life','education','utilities'];
const symbols:Record<string,string>={health:'✚',transportation:'↗',quality_of_life:'❋',education:'◇',utilities:'ϟ',budget:'€',housing:'⌂'};
const initialProfile:Profile={bedrooms:2,tenure:'rent',budget:'',ages:'',mode:'driving',car:true,radiusKm:10};
const prettify=(s:string)=>s.replace(/_/g,' ');
const money=(n:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
export function App(){
 const [step,setStep]=useState(0),[registry,setRegistry]=useState<Criterion[]>([]),[status,setStatus]=useState<any>(null),[query,setQuery]=useState(''),[places,setPlaces]=useState<Place[]>([]),[place,setPlace]=useState<Place|null>(null),[origin,setOrigin]=useState<{longitude:number;latitude:number}|null>(null),[anchorLabel,setAnchorLabel]=useState('Town boundary anchor'),[profile,setProfile]=useState(initialProfile),[choices,setChoices]=useState<Record<string,Choice>>({}),[layers,setLayers]=useState<any[]>([]),[assessment,setAssessment]=useState<any>(null),[regions,setRegions]=useState<Place[]>([]),[selected,setSelected]=useState(''),[pillar,setPillar]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[cart,setCart]=useState(false),[marketRegions,setMarketRegions]=useState<any[]>([]),[marketRegion,setMarketRegion]=useState(''),[market,setMarket]=useState<any[]>([]),[marketError,setMarketError]=useState('');
 useEffect(()=>{const abort=new AbortController();Promise.all([api('/criteria',undefined,abort.signal),api('/data-status',undefined,abort.signal)]).then(([criteria,data])=>{setRegistry(criteria.criteria);setStatus(data);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{if(!query.trim()){setPlaces([]);return;}const abort=new AbortController();const timer=setTimeout(()=>api(`/places?q=${encodeURIComponent(query)}&limit=8`,undefined,abort.signal).then(r=>setPlaces(r.places)).catch(e=>{if(e.name!=='AbortError')setError(e.message);}),200);return()=>{clearTimeout(timer);abort.abort();};},[query]);
 const loadMarketRegions=async()=>{setMarketError('');try{const r=await api(`/market-geographies?tenure=${profile.tenure}&limit=1000`);setMarketRegions(r.geographies??r.regions??[]);}catch{setMarketRegions([]);setMarketError('Market-region data is temporarily unavailable. Retry when the data service is ready.');}};
 useEffect(()=>{if(step!==4)return;void loadMarketRegions();setMarketRegion('');setMarket([]);},[profile.tenure,step]);
 const choosePlace=async(p:Place)=>{setPlace(p);setQuery(p.name);setPlaces([]);setError('');let anchor=boundaryAnchor(p);let caption='Town boundary anchor';try{const result=await api(`/place-anchor?placeId=${encodeURIComponent(p.id)}`);anchor=result.location??result.anchor??{longitude:result.longitude,latitude:result.latitude};caption='Representative town anchor';}catch{/* Clearly labelled source-boundary fallback. */}setOrigin(anchor);setAnchorLabel(caption);setLayers([]);setAssessment(null);setSelected('');if(step===4)await load(p,anchor);};
 const updateProfile=(patch:Partial<Profile>)=>setProfile(p=>({...p,...patch}));
 const toggle=(id:string)=>setChoices(previous=>{const next={...previous};if(next[id])delete next[id];else next[id]={importance:'preferred'};return next;});
 const changeChoice=(id:string,patch:Partial<Choice>)=>setChoices(p=>({...p,[id]:{...p[id],...patch}}));
 const load=async(p=place,o=origin)=>{if(!p||!o||!Object.keys(choices).length)return;setLoading(true);setError('');try{const prefs=preferences(o,p,profile,choices,registry);const [layerResult,assessResult,nearby]=await Promise.all([api('/layers',{...prefs,limit:40}),api('/assess',prefs),api(`/features?longitude=${o.longitude}&latitude=${o.latitude}&radiusM=50000&categories=urban_area&limit=7`)]);setLayers(layerResult.layers);setAssessment(assessResult);setRegions([p,...nearby.data.features.map((f:any)=>({...f.properties,geometry:f.geometry})).filter((r:Place)=>r.id!==p.id)].slice(0,7));setSelected(layerResult.layers[0]?.id??'');setStep(4);}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
 const activeLayer=layers.find(l=>l.id===selected);const visibleLayers=pillar?layers.filter(l=>l.vertical===pillar):layers;const mapFeatures=activeLayer?.data.features??[];
 const readMarket=async(value:string)=>{setMarketRegion(value);setMarket([]);if(!value)return;const region=marketRegions.find(r=>(r.codeSystem??r.geography?.codeSystem)+'|'+(r.code??r.geography?.code)===value);if(!region)return;const code=region.code??region.geography.code,codeSystem=region.codeSystem??region.geography.codeSystem;try{const response=await api(`/market-context?geographyCode=${encodeURIComponent(code)}&geographyCodeSystem=${encodeURIComponent(codeSystem)}&tenure=${profile.tenure}${region.latestPeriod?`&period=${encodeURIComponent(region.latestPeriod)}`:''}&limit=250`);const records=response.records.filter((r:any)=>r.attributes.amountEur!==null).sort((a:any,b:any)=>b.attributes.period.localeCompare(a.attributes.period));setMarket(records.slice(0,8));}catch(e){setError((e as Error).message);}};
 const selectedMarketRegion=marketRegions.find(r=>(r.codeSystem??r.geography?.codeSystem)+'|'+(r.code??r.geography?.code)===marketRegion);
 const bedroomClassLabel=(code:string)=>selectedMarketRegion?.bedroomClasses?.find((entry:{code:string;label:string})=>String(entry.code)===String(code))?.label??`Bedroom class ${code}`;
 const badge=Object.keys(choices).length;
 return <div className={step===4?'live-app dashboard-mode':'live-app profile-setup'}>
  <header className="map-header"><a className="brand" href="/"><span className="brand-pin">⌖</span><span>Find your place<small>IRELAND</small></span></a><div className="header-actions"><button onClick={()=>setCart(!cart)}>Your profile <small className="pill">{badge}</small></button>{step===4&&<button onClick={()=>setStep(3)}>Edit priorities</button>}<button onClick={()=>{setStep(0);setPlace(null);setOrigin(null);setChoices({});setLayers([]);setAssessment(null);setProfile(initialProfile);setQuery('');}}>Start again</button></div></header>
  {error&&<div className="service-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}
  {step<4&&<section className="prompt"><div className="question-top"><span className="eyebrow">{step===3?'Your service priorities':'Your household profile'}</span><span className="question-location">Step {step+1} of 4</span></div>
   {step===0&&<><h1>Where do you have in mind?</h1><p className="question-hint">Choose a town or city in Ireland. We’ll start with the evidence around it.</p><label className="input-label"><span>Town or city</span><input autoFocus placeholder="Try Drogheda, Cork or Galway" value={query} onChange={e=>{setQuery(e.target.value);setPlace(null);}}/></label><div className="place-results">{places.map(p=><button key={p.id} className={`choice ${place?.id===p.id?'selected':''}`} onClick={()=>choosePlace(p)}><strong>{p.name}</strong><small>{p.attributes.county??'CSO urban area'}</small></button>)}</div>{place&&<p className="selection-note">✓ {place.name} selected · Census 2022 boundary</p>}<p className="fine-note">CSO urban areas cover towns and cities. Rural localities may not appear.</p></>}
   {step===1&&<><h1>Who are you finding a home for?</h1><p className="question-hint">Your household needs shape your choices. These answers stay in memory during this visit.</p><div className="profile-fields"><label>Bedrooms<input type="number" min="1" max="12" value={profile.bedrooms} onChange={e=>updateProfile({bedrooms:Math.max(1,Number(e.target.value))})}/></label><label>Children’s ages (optional)<input placeholder="For example: 3, 8" value={profile.ages} onChange={e=>updateProfile({ages:e.target.value})}/></label><label>Looking to<select value={profile.tenure} onChange={e=>updateProfile({tenure:e.target.value as 'buy'|'rent'})}><option value="rent">Rent</option><option value="buy">Buy</option></select></label><label>{profile.tenure==='rent'?'Monthly budget (€)':'Purchase budget (€)'}<input type="number" min="1" placeholder={profile.tenure==='rent'?'1800':'350000'} value={profile.budget} onChange={e=>updateProfile({budget:e.target.value})}/></label></div><p className="fine-note">Historical prices are area context. Available homes and bedroom matches are not verified.</p></>}
   {step===2&&<><h1>How do you get around?</h1><p className="question-hint">Choose your everyday mode and the area you want to explore.</p><div className="choices">{[['driving','Car'],['public_transport','Public transport'],['cycling','Cycling'],['walking','Walking']].map(([value,name])=><button key={value} className={`choice ${profile.mode===value?'selected':''}`} onClick={()=>updateProfile({mode:value as Profile['mode']})}>{name}</button>)}</div><label className="radio-filter"><input type="checkbox" checked={profile.car} onChange={e=>updateProfile({car:e.target.checked})}/>A car is available to my household</label><label className="input-label"><span>Explore within {profile.radiusKm} km of the search anchor</span><input type="range" min="1" max="50" value={profile.radiusKm} onChange={e=>updateProfile({radiusKm:Number(e.target.value)})}/></label><p className="fine-note">Journey times need routing and timetables. Map distances alone do not verify access.</p></>}
   {step===3&&<><h1>What matters to you?</h1><p className="question-hint">Choose any number of criteria, then mark what is required or preferred.</p><Criteria registry={registry} choices={choices} toggle={toggle} change={changeChoice}/></>}
   <div className="question-actions"><button className="back" disabled={step===0} onClick={()=>setStep(step-1)}>← Back</button><button className="primary" disabled={loading||(step===0&&!place)||(step===3&&!badge)||!registry.length} onClick={()=>step===3?load():setStep(step+1)}>{loading?'Reading source evidence…':step===3?'Explore this area →':'Continue →'}</button></div></section>}
  {step===4&&place&&origin&&<><aside className="filters visible"><div className="filters-heading"><div><h2>Service priorities</h2><p>{place.name} · {profile.radiusKm} km</p></div></div><Criteria registry={registry} choices={choices} toggle={toggle} change={changeChoice}/><button className="primary apply" disabled={loading||!badge} onClick={()=>load()}>{loading?'Updating…':'Update evidence'}</button><p className="filter-footnote">Required criteria are saved as preferences. Eligibility and fit remain unknown.</p></aside>
  <main className="dashboard"><div className="results-context"><span>{place.name} · {profile.tenure==='rent'?'Renting':'Buying'} · {profile.bedrooms}+ bedrooms</span><button onClick={()=>setStep(0)}>Change location</button></div><div className="results-title"><div><h1>Places to explore</h1><p>Real source records, with the gaps made visible.</p></div><span className="context-badge">Fit score: unknown</span></div><div className="kpi-strip"><div><strong>{status?.totalRecords?.toLocaleString('en-IE')??'—'}</strong><span>Source records across Ireland</span></div><div><strong>{badge}</strong><span>Selected criteria</span></div><div><strong>{layers.reduce((n,l)=>n+l.data.features.length,0)}</strong><span>Displayed records · first pages</span></div></div>
  <div className="region-grid live-regions">{regions.map(r=><button key={r.id} className={`region-card ${r.id===place.id?'active':''}`} onClick={()=>choosePlace(r)}><div className="region-card-top"><span><strong>{r.name}</strong><small>{r.attributes.county??'CSO urban area'}</small></span><span className="region-score">—<small>Fit unknown</small></span></div><p className="region-card-note">{r.id===place.id?'Current evidence area':'Explore recorded services'}</p><span className="region-link">View source evidence ↗</span></button>)}</div><p className="fine-note">Nearby urban areas are ordered by recorded geography distance, without a suitability ranking.</p>
  <div className="pillar-scores">{five.map(v=><button key={v} className={`pillar-score ${pillar===v?'active':''}`} onClick={()=>setPillar(pillar===v?'':v)}><span>{pillarLabels[v]}</span><strong>—</strong><small>{layers.filter(l=>l.vertical===v).length} selected · score unknown</small></button>)}</div>
  <div className="detail-content"><section className="reason-panel"><div><h2>{pillar?pillarLabels[pillar]:'Your criteria'}</h2><button onClick={()=>setPillar('')}>Show all</button></div><div className="criterion-rows">{visibleLayers.map(l=><button key={l.id} className={`criterion-row ${selected===l.id?'active':''}`} onClick={()=>setSelected(l.id)}><span><strong>{label(registry.find(c=>c.id===l.id)!)}</strong><small>{choices[l.id]?.importance??'Preferred'} · {l.data.features.length} displayed{l.nextCursor?' · more available':''}</small></span><span><strong>—</strong><small>{l.evidenceStatus==='unknown'?'Evidence unknown':'Partial source coverage'}</small></span><span>›</span></button>)}</div></section>
  <section className="criterion-detail"><div className="criterion-detail-heading"><span>{activeLayer?label(registry.find(c=>c.id===selected)!):'Area map'}</span><small>Recorded features</small></div><MapView place={place} origin={origin} features={mapFeatures} onPick={point=>{setOrigin(point);setAnchorLabel('Point selected on map');setLayers([]);setAssessment(null);}}/><p className="map-demo-note">{anchorLabel}. Click the map to choose your own search point, then update evidence.</p>{activeLayer&&<><div className="criterion-facts"><strong>{activeLayer.data.features.length} displayed</strong><p>{assessment?.results.find((r:any)=>r.id===selected)?.reason??activeLayer.explanation}</p></div><div className="source-records">{activeLayer.data.features.slice(0,12).map((f:any)=><div key={f.id}><strong>{f.properties.name}</strong><small>{f.properties.observedPeriod??'Observation date unknown'} · {prettify(f.properties.category)}{Number.isFinite(f.properties.recordedGeometryDistanceM)?` · ${(f.properties.recordedGeometryDistanceM/1000).toFixed(1)} km from anchor`:''}</small></div>)}</div><details className="source-details"><summary>Sources, dates and limitations ({activeLayer.sources.length})</summary>{activeLayer.sources.map((source:any)=><div key={source.snapshotId}><strong>{source.publisher}</strong><p>Observed: {source.observedPeriod??'unknown'} · {source.license}</p><p>{source.limitations.join(' ')}</p><a href={source.sourceUrl} target="_blank" rel="noreferrer">Publisher source ↗</a></div>)}</details></>}</section></div>
  <section className="budget-panel"><h2>Housing budget context</h2><p>{profile.bedrooms}+ bedrooms{profile.budget?` · ${money(Number(profile.budget))}${profile.tenure==='rent'?' / month':''}`:''} · {profile.tenure==='rent'?'Renting':'Buying'}</p><label>Choose the publisher’s market region explicitly<select value={marketRegion} onChange={e=>readMarket(e.target.value)}><option value="">{marketRegions.length?'Select a source geography':'Market-region selection is loading or unavailable'}</option>{marketRegions.map(r=>{const g=r.geography??r;return <option key={`${g.codeSystem}|${g.code}`} value={`${g.codeSystem}|${g.code}`}>{g.name} · {g.codeSystem}</option>;})}</select></label>{marketError&&<p className="market-error" role="alert">{marketError} <button onClick={()=>void loadMarketRegions()}>Retry market data</button></p>}<p className="fine-note">The town has no verified market-region crosswalk. This choice does not claim a bedroom match or home availability. Observations below include multiple bedroom classes; they are not filtered to your household.</p><div className="market-grid">{market.map(r=><div key={r.id}><strong>{money(r.attributes.amountEur)}{r.attributes.unit==='EUR/month'?' / month':''}</strong><span>{prettify(r.attributes.statistic)} · {r.attributes.propertyTypeLabel}</span><small>{r.attributes.geography.name} · {r.attributes.period}{r.attributes.bedroomClass?` · ${bedroomClassLabel(r.attributes.bedroomClass)}`:''}</small></div>)}</div></section>
  <p className="results-footnote">Sources have different dates and coverage. Missing data is unknown. Travel times, home availability, suitability and utility connections are not certified.</p></main></>}
  {cart&&<aside className="profile-cart"><div className="cart-heading"><h2>Your household profile</h2><button onClick={()=>setCart(false)} aria-label="Close profile">×</button></div><div className="cart-profile"><strong>{place?.name??'Location not selected'}</strong><small>{profile.bedrooms}+ bedrooms · {profile.tenure==='rent'?'Renting':'Buying'}</small><small>{profile.mode.replace('_',' ')} · {profile.car?'Car available':'No car'}</small><small>{profile.ages?`Children’s ages: ${profile.ages}`:'Children’s ages not specified'}</small></div><div className="cart-criteria"><h3>Selected priorities <span>{badge}</span></h3>{Object.entries(choices).map(([id,c])=><div className="cart-item" key={id}><span>{label(registry.find(d=>d.id===id)!)}<small>{c.importance}</small></span><button onClick={()=>toggle(id)} aria-label={`Remove ${id}`}>×</button></div>)}</div><p className="fine-note">Your profile is held in memory for this visit.</p></aside>}
 </div>;
}
function Criteria({registry,choices,toggle,change}:{registry:Criterion[];choices:Record<string,Choice>;toggle:(id:string)=>void;change:(id:string,patch:Partial<Choice>)=>void}){return <div className="criteria-editor">{[...new Set(registry.map(c=>c.vertical))].map(vertical=><details key={vertical} className="filter-section" open><summary><i>{symbols[vertical]??'⌂'}</i>{pillarLabels[vertical]??prettify(vertical)}<span>⌄</span></summary><div>{registry.filter(c=>c.vertical===vertical).map(c=><div className="criterion-filter" key={c.id}><label className="radio-filter"><input type="checkbox" checked={Boolean(choices[c.id])} onChange={()=>toggle(c.id)}/>{label(c)}</label>{choices[c.id]&&<><select aria-label={`${label(c)} importance`} value={choices[c.id].importance} onChange={e=>change(c.id,{importance:e.target.value as Choice['importance']})}><option value="preferred">Preferred</option><option value="required">Required</option></select>{c.method==='travel_time'&&<label className="small-input"><span>Maximum journey</span><select value={choices[c.id].maximumMinutes??Number(c.defaults.maximumMinutes??30)} onChange={e=>change(c.id,{maximumMinutes:Number(e.target.value)})}>{[15,30,60,90].map(m=><option key={m} value={m}>{m} min</option>)}</select></label>}{c.id==='health.hospital'&&<label className="small-input"><span>Clinical service</span><input placeholder="Optional, e.g. cardiology" value={choices[c.id].requiredService??''} onChange={e=>change(c.id,{requiredService:e.target.value})}/></label>}{c.id==='utilities.broadband'&&<label className="small-input"><span>Minimum speed</span><select value={choices[c.id].minimumDownloadMbps??100} onChange={e=>change(c.id,{minimumDownloadMbps:Number(e.target.value)})}>{[100,500,1000].map(n=><option key={n} value={n}>{n} Mbps</option>)}</select></label>}{c.method==='distance'&&<label className="small-input"><span>Desired distance</span><select value={choices[c.id].maximumDistanceM??2000} onChange={e=>change(c.id,{maximumDistanceM:Number(e.target.value)})}>{[500,1000,2000,5000].map(m=><option key={m} value={m}>{m/1000} km</option>)}</select></label>}</>}</div>)}</div></details>)}</div>;}
