import {useCallback,useEffect,useRef,useState} from 'react';
import {api,boundaryAnchor,label,pillarLabels,preferences,type Choice,type Criterion,type Place,type Profile} from './domain';
import {MapView} from './Map';
import {Onboarding} from './Onboarding';
import {freshDraft, readProfile, saveProfile, transportModes, type Draft, type SavedProfile} from './onboarding-model';
const five=['health','transportation','quality_of_life','education','utilities'];
const symbols:Record<string,string>={health:'✚',transportation:'↗',quality_of_life:'❋',education:'◇',utilities:'ϟ',budget:'€',housing:'⌂'};
const initialProfile:Profile={bedrooms:2,tenure:'rent',budget:'',ages:'',mode:'driving',car:true,radiusKm:10};
const prettify=(s:string)=>s.replace(/_/g,' ');
const money=(n:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
export function App(){
 const [saved,setSaved]=useState<SavedProfile|null>(()=>{try{return readProfile(localStorage);}catch{return null;}});
 const [draft,setDraft]=useState<Draft>(()=>saved?.draft??freshDraft());
 const [setupKey,setSetupKey]=useState(0);
 const requestVersion=useRef(0);
 const [scope,setScope]=useState(saved?.draft.scope??null);
 const [step,setStep]=useState(saved?3:0),[registry,setRegistry]=useState<Criterion[]>([]),[status,setStatus]=useState<any>(null),[place,setPlace]=useState<Place|null>(saved?.draft.scope==='specific'?saved.draft.place:null),[origin,setOrigin]=useState<{longitude:number;latitude:number}|null>(null),[anchorLabel,setAnchorLabel]=useState('Town boundary anchor'),[profile,setProfile]=useState(saved?.profile??initialProfile),[choices,setChoices]=useState<Record<string,Choice>>({}),[layers,setLayers]=useState<any[]>([]),[assessment,setAssessment]=useState<any>(null),[regions,setRegions]=useState<Place[]>([]),[selected,setSelected]=useState(''),[pillar,setPillar]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[cart,setCart]=useState(false),[marketRegions,setMarketRegions]=useState<any[]>([]),[marketRegion,setMarketRegion]=useState(''),[market,setMarket]=useState<any[]>([]),[marketError,setMarketError]=useState('');
 useEffect(()=>{const abort=new AbortController();Promise.all([api('/criteria',undefined,abort.signal),api('/data-status',undefined,abort.signal)]).then(([criteria,data])=>{setRegistry(criteria.criteria);setStatus(data);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 const loadMarketRegions=async()=>{setMarketError('');try{const r=await api(`/market-geographies?tenure=${profile.tenure}&limit=1000`);setMarketRegions(r.geographies??r.regions??[]);}catch{setMarketRegions([]);setMarketError('Market-region data is temporarily unavailable. Retry when the data service is ready.');}};
 useEffect(()=>{if(step!==4)return;void loadMarketRegions();setMarketRegion('');setMarket([]);},[profile.tenure,step]);
 const choosePlace=async(p:Place)=>{const version=++requestVersion.current;setPlace(p);setError('');let anchor=boundaryAnchor(p);let caption='Town boundary anchor';try{const result=await api(`/place-anchor?placeId=${encodeURIComponent(p.id)}`);anchor=result.location??result.anchor??{longitude:result.longitude,latitude:result.latitude};caption='Representative town anchor';}catch{/* Clearly labelled source-boundary fallback. */}if(version!==requestVersion.current)return;setOrigin(anchor);setAnchorLabel(caption);setLayers([]);setAssessment(null);setSelected('');if(step===4||step===5)await load(p,anchor);};
 const onDraftChange=useCallback((value:Draft)=>setDraft(value),[]);
 const finishOnboarding=(value:Draft)=>{const bundle=saveProfile(value,localStorage);requestVersion.current++;setLoading(false);setSaved(bundle);setProfile(bundle.profile);setScope(value.scope);setPlace(value.scope==='specific'?value.place:null);setOrigin(null);setLayers([]);setAssessment(null);setStep(3);setCart(false);setError('');};
 const startSetup=(edit=false)=>{requestVersion.current++;setLoading(false);setDraft(edit&&saved?structuredClone(saved.draft):freshDraft());setSetupKey(k=>k+1);setStep(0);setCart(false);setError('');if(!edit){setChoices({});setLayers([]);setAssessment(null);setPlace(null);setOrigin(null);setScope(null);setProfile(initialProfile);}};
 const browseRegions=async()=>{
  const version=++requestVersion.current;
  setLoading(true);setError('');
  try{
   let cursor:string|null=null;
   const all:Place[]=[];
   do{
    const result=await api(`/features?bbox=-11,51,-5,56&categories=urban_area&limit=250${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`);
    if(version!==requestVersion.current)return;
    all.push(...result.data.features.map((f:any)=>({...f.properties,geometry:f.geometry})));
    cursor=result.nextCursor??null;
   }while(cursor);
   setRegions(all);setStep(5);
  }catch(e){if(version===requestVersion.current)setError((e as Error).message);}
  finally{if(version===requestVersion.current)setLoading(false);}
 };


 const toggle=(id:string)=>setChoices(previous=>{const next={...previous};if(next[id])delete next[id];else next[id]={importance:'preferred'};return next;});
 const changeChoice=(id:string,patch:Partial<Choice>)=>setChoices(p=>({...p,[id]:{...p[id],...patch}}));
 const load=async(p=place,o=origin)=>{
  if(!p)return;
  const version=++requestVersion.current;
  setLoading(true);setError('');
  try{
   if(!o){
    o=boundaryAnchor(p);setAnchorLabel('Town boundary anchor');
    try{
     const anchor=await api(`/place-anchor?placeId=${encodeURIComponent(p.id)}`);
     o=anchor.location??anchor.anchor??{longitude:anchor.longitude,latitude:anchor.latitude};
     if(version!==requestVersion.current)return;
     setAnchorLabel('Representative town anchor');
    }catch{/* The boundary fallback stays labelled. */}
    if(version!==requestVersion.current)return;
    setOrigin(o);
   }
   if(!o)throw new Error('Choose a search point before loading evidence.');
   const prefs=preferences(o,p,profile,choices,registry);
   // The API requires a criterion. An empty selection opens only the area map.
   const [layerResult,assessResult,nearby]=await Promise.all([
    prefs.criteria.length?api('/layers',{...prefs,limit:40}):Promise.resolve({layers:[]}),
    prefs.criteria.length?api('/assess',prefs):Promise.resolve(null),
    api(`/features?longitude=${o.longitude}&latitude=${o.latitude}&radiusM=50000&categories=urban_area&limit=7`),
   ]);
   if(version!==requestVersion.current)return;
   setLayers(layerResult.layers);setAssessment(assessResult);
   setRegions([p,...nearby.data.features.map((f:any)=>({...f.properties,geometry:f.geometry})).filter((r:Place)=>r.id!==p.id)].slice(0,7));
   setSelected(layerResult.layers[0]?.id??'');setStep(4);
  }catch(e){if(version===requestVersion.current)setError((e as Error).message);}
  finally{if(version===requestVersion.current)setLoading(false);}
 };

 const activeLayer=layers.find(l=>l.id===selected);const visibleLayers=pillar?layers.filter(l=>l.vertical===pillar):layers;const mapFeatures=activeLayer?.data.features??[];
 const readMarket=async(value:string)=>{setMarketRegion(value);setMarket([]);if(!value)return;const region=marketRegions.find(r=>(r.codeSystem??r.geography?.codeSystem)+'|'+(r.code??r.geography?.code)===value);if(!region)return;const code=region.code??region.geography.code,codeSystem=region.codeSystem??region.geography.codeSystem;try{const response=await api(`/market-context?geographyCode=${encodeURIComponent(code)}&geographyCodeSystem=${encodeURIComponent(codeSystem)}&tenure=${profile.tenure}${region.latestPeriod?`&period=${encodeURIComponent(region.latestPeriod)}`:''}&limit=250`);const records=response.records.filter((r:any)=>r.attributes.amountEur!==null).sort((a:any,b:any)=>b.attributes.period.localeCompare(a.attributes.period));setMarket(records.slice(0,8));}catch(e){setError((e as Error).message);}};
 const selectedMarketRegion=marketRegions.find(r=>(r.codeSystem??r.geography?.codeSystem)+'|'+(r.code??r.geography?.code)===marketRegion);
 const bedroomClassLabel=(code:string)=>selectedMarketRegion?.bedroomClasses?.find((entry:{code:string;label:string})=>String(entry.code)===String(code))?.label??`Bedroom class ${code}`;
 const badge=Object.keys(choices).length;
 const searchContext=step===0?{scope:draft.scope,place:draft.place,bedrooms:draft.bedrooms,tenure:draft.tenure,budget:draft.budgets[draft.tenure]}:{scope,place,bedrooms:profile.bedrooms,tenure:profile.tenure,budget:profile.budget};
 return <div className={step===0?'live-app profile-setup':step===3?'live-app service-selection':'live-app dashboard-mode'}>
  <header className="map-header"><a className="brand" href="/"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg><span>Find your place<small>IRELAND</small></span></a><div className="header-actions"><button className="cart-toggle" aria-expanded={cart} onClick={()=>setCart(!cart)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M3 3h2l3 12h11l2-8H6M9 20h1m7 0h1"/></svg>Your profile <small>{(saved?.profile.people??draft.people).length}</small></button>{step!==0&&step!==3&&<button onClick={()=>{requestVersion.current++;setLoading(false);setStep(3);}}>Edit priorities</button>}<button onClick={()=>startSetup()}>Start again</button></div></header>
  {error&&<div className="service-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}
  {step===0&&<Onboarding key={setupKey} initial={draft} onSave={finishOnboarding} onDraftChange={onDraftChange}/>}
  {step===3&&<main className="dashboard service-dashboard"><div className="service-intro"><h1>What matters to you?</h1><p>Choose the services that matter to your household. Mark each as required or preferred.</p></div>{!registry.length?<p className="fine-note" role="status">{error?'Service priorities are unavailable while the data service is offline. Your profile is saved.':'Loading service priorities…'}</p>:<Criteria fullScreen registry={registry} choices={choices} toggle={toggle} change={changeChoice}/>}<div className="service-continue"><span><strong>{badge} {badge===1?'service selected':'services selected'}</strong><small>{scope==='anywhere'?'Anywhere in Ireland':place?.name} · Your household profile is saved</small></span><button className="primary" disabled={loading||!registry.length} onClick={()=>scope==='anywhere'?browseRegions():load()}>{loading?'Reading source evidence…':scope==='anywhere'?'Explore regions →':'Explore this area →'}</button></div></main>}
  {step===5&&<main className="dashboard all-regions"><div className="results-title"><div><h1>Regions to explore</h1><p>Choose a region to see its recorded service evidence.</p></div><span className="context-badge">{regions.length} towns and cities</span></div><div className="region-grid">{regions.map(r=><button className="region-card" disabled={loading} key={r.id} onClick={()=>choosePlace(r)}><div className="region-card-top"><span><strong>{r.name}</strong><small>{r.attributes.county??'CSO urban area'}</small></span></div><span className="region-link">View source evidence ↗</span></button>)}</div><p className="fine-note">CSO urban areas cover towns and cities. Rural localities may not appear. Suitability remains unknown.</p></main>}
  {step===4&&place&&origin&&<><aside className="filters visible"><div className="filters-heading"><div><h2>Service priorities</h2><p>{place.name} · {profile.radiusKm} km</p></div></div><label className="small-input"><span>Search radius</span><select aria-label="Search radius" value={profile.radiusKm} onChange={e=>setProfile(p=>({...p,radiusKm:Number(e.target.value)}))}>{[1,5,10,25,50].map(n=><option key={n} value={n}>{n} km</option>)}</select></label><Criteria registry={registry} choices={choices} toggle={toggle} change={changeChoice}/><button className="primary apply" disabled={loading||!badge} onClick={()=>load()}>{loading?'Updating…':'Update evidence'}</button><p className="filter-footnote">Required criteria are saved as preferences. Eligibility and fit remain unknown.</p></aside>
  <main className="dashboard"><div className="results-context"><span>{place.name} · {profile.tenure==='rent'?'Renting':'Buying'} · {profile.bedrooms}+ bedrooms</span><button onClick={()=>{setScope('anywhere');void browseRegions();}}>Change location</button></div><div className="results-title"><div><h1>Places to explore</h1><p>Real source records, with the gaps made visible.</p></div><span className="context-badge">Fit score: unknown</span></div><div className="kpi-strip"><div><strong>{status?.totalRecords?.toLocaleString('en-IE')??'—'}</strong><span>Source records across Ireland</span></div><div><strong>{badge}</strong><span>Selected criteria</span></div><div><strong>{layers.reduce((n,l)=>n+l.data.features.length,0)}</strong><span>Displayed records · first pages</span></div></div>
  <div className="region-grid live-regions">{regions.map(r=><button key={r.id} className={`region-card ${r.id===place.id?'active':''}`} onClick={()=>choosePlace(r)}><div className="region-card-top"><span><strong>{r.name}</strong><small>{r.attributes.county??'CSO urban area'}</small></span><span className="region-score">—<small>Fit unknown</small></span></div><p className="region-card-note">{r.id===place.id?'Current evidence area':'Explore recorded services'}</p><span className="region-link">View source evidence ↗</span></button>)}</div><p className="fine-note">Nearby urban areas are ordered by recorded geography distance, without a suitability ranking.</p>
  <div className="pillar-scores">{five.map(v=><button key={v} className={`pillar-score ${pillar===v?'active':''}`} onClick={()=>setPillar(pillar===v?'':v)}><span>{pillarLabels[v]}</span><strong>—</strong><small>{layers.filter(l=>l.vertical===v).length} selected · score unknown</small></button>)}</div>
  <div className="detail-content"><section className="reason-panel"><div><h2>{pillar?pillarLabels[pillar]:'Your criteria'}</h2><button onClick={()=>setPillar('')}>Show all</button></div><div className="criterion-rows">{visibleLayers.map(l=><button key={l.id} className={`criterion-row ${selected===l.id?'active':''}`} onClick={()=>setSelected(l.id)}><span><strong>{label(registry.find(c=>c.id===l.id)!)}</strong><small>{choices[l.id]?.importance??'Preferred'} · {l.data.features.length} displayed{l.nextCursor?' · more available':''}</small></span><span><strong>—</strong><small>{l.evidenceStatus==='unknown'?'Evidence unknown':'Partial source coverage'}</small></span><span>›</span></button>)}</div></section>
  <section className="criterion-detail"><div className="criterion-detail-heading"><span>{activeLayer?label(registry.find(c=>c.id===selected)!):'Area map'}</span><small>Recorded features</small></div><MapView place={place} origin={origin} features={mapFeatures} onPick={point=>{setOrigin(point);setAnchorLabel('Point selected on map');setLayers([]);setAssessment(null);}}/><p className="map-demo-note">{anchorLabel}. Click the map to choose your own search point, then update evidence.</p>{activeLayer&&<><div className="criterion-facts"><strong>{activeLayer.data.features.length} displayed</strong><p>{assessment?.results.find((r:any)=>r.id===selected)?.reason??activeLayer.explanation}</p></div><div className="source-records">{activeLayer.data.features.slice(0,12).map((f:any)=><div key={f.id}><strong>{f.properties.name}</strong><small>{f.properties.observedPeriod??'Observation date unknown'} · {prettify(f.properties.category)}{Number.isFinite(f.properties.recordedGeometryDistanceM)?` · ${(f.properties.recordedGeometryDistanceM/1000).toFixed(1)} km from anchor`:''}</small></div>)}</div><details className="source-details"><summary>Sources, dates and limitations ({activeLayer.sources.length})</summary>{activeLayer.sources.map((source:any)=><div key={source.snapshotId}><strong>{source.publisher}</strong><p>Observed: {source.observedPeriod??'unknown'} · {source.license}</p><p>{source.limitations.join(' ')}</p><a href={source.sourceUrl} target="_blank" rel="noreferrer">Publisher source ↗</a></div>)}</details></>}</section></div>
  <section className="budget-panel"><h2>Housing budget context</h2><p>{profile.bedrooms}+ bedrooms{profile.budget?` · ${money(Number(profile.budget))}${profile.tenure==='rent'?' / month':''}`:''} · {profile.tenure==='rent'?'Renting':'Buying'}</p><label>Choose the publisher’s market region explicitly<select value={marketRegion} onChange={e=>readMarket(e.target.value)}><option value="">{marketRegions.length?'Select a source geography':'Market-region selection is loading or unavailable'}</option>{marketRegions.map(r=>{const g=r.geography??r;return <option key={`${g.codeSystem}|${g.code}`} value={`${g.codeSystem}|${g.code}`}>{g.name} · {g.codeSystem}</option>;})}</select></label>{marketError&&<p className="market-error" role="alert">{marketError} <button onClick={()=>void loadMarketRegions()}>Retry market data</button></p>}<p className="fine-note">The town has no verified market-region crosswalk. This choice does not claim a bedroom match or home availability. Observations below include multiple bedroom classes; they are not filtered to your household.</p><div className="market-grid">{market.map(r=><div key={r.id}><strong>{money(r.attributes.amountEur)}{r.attributes.unit==='EUR/month'?' / month':''}</strong><span>{prettify(r.attributes.statistic)} · {r.attributes.propertyTypeLabel}</span><small>{r.attributes.geography.name} · {r.attributes.period}{r.attributes.bedroomClass?` · ${bedroomClassLabel(r.attributes.bedroomClass)}`:''}</small></div>)}</div></section>
  <p className="results-footnote">Sources have different dates and coverage. Missing data is unknown. Travel times, home availability, suitability and utility connections are not certified.</p></main></>}
  {cart&&<aside className="profile-cart" aria-label="Household profile"><div className="cart-heading"><div><h2>{saved?'Your saved profile':'Your household profile'}</h2><p>{saved?'Saved in this browser':'Selections you’re building'}</p></div><button onClick={()=>setCart(false)} aria-label="Close profile">×</button></div><div className="cart-profile"><span className="cart-lock">{saved?'✓ Saved defaults':'Profile in progress'}</span><strong>{(saved?.profile.people??draft.people).length} {(saved?.profile.people??draft.people).length===1?'person':'people'} in your household</strong><small>Ages: {(saved?.profile.people??draft.people).map(p=>p.age===null?'not specified':p.age).join(', ')}</small><dl><div><dt>Main transport</dt><dd>{transportModes.find(([mode])=>mode===(saved?.profile.mode??draft.mode))?.[1]??'Not chosen'}</dd></div><div><dt>Car available</dt><dd>{(saved?.profile.car??draft.car)===null?'Not chosen':(saved?.profile.car??draft.car)?'Yes':'No'}</dd></div></dl></div>{saved&&<button className="edit-profile" onClick={()=>startSetup(true)}>Edit saved profile</button>}<div className="cart-criteria"><h3>Current selections <span>{badge}</span></h3><div className="cart-search-context"><span>{searchContext.scope==='anywhere'?'Anywhere in Ireland':searchContext.place?.name??'Location not chosen'}</span><small>{searchContext.bedrooms?`${searchContext.bedrooms}+ bedrooms · `:''}{searchContext.tenure==='rent'?'Renting':'Buying'}{searchContext.budget?` · ${money(Number(searchContext.budget))}${searchContext.tenure==='rent'?' / month':''}`:''}</small></div>{Object.entries(choices).map(([id,c])=><div className="cart-item" key={id}><span>{label(registry.find(d=>d.id===id)!)}<small>{c.importance}</small></span><button onClick={()=>toggle(id)} aria-label={`Remove ${id}`}>×</button></div>)}</div></aside>}

 </div>;
}
function Criteria({registry,choices,toggle,change,fullScreen=false}:{fullScreen?:boolean;registry:Criterion[];choices:Record<string,Choice>;toggle:(id:string)=>void;change:(id:string,patch:Partial<Choice>)=>void}){return <div className={fullScreen?'criteria-editor service-grid':'criteria-editor'}>{[...new Set(registry.map(c=>c.vertical))].map(vertical=><details key={vertical} className={fullScreen?'filter-section service-pillar':'filter-section'} open><summary><i>{symbols[vertical]??'⌂'}</i>{pillarLabels[vertical]??prettify(vertical)}<span>⌄</span></summary><div>{registry.filter(c=>c.vertical===vertical).map(c=><div className="criterion-filter" key={c.id}><label className="radio-filter"><input type="checkbox" checked={Boolean(choices[c.id])} onChange={()=>toggle(c.id)}/>{label(c)}</label>{choices[c.id]&&<><select aria-label={`${label(c)} importance`} value={choices[c.id].importance} onChange={e=>change(c.id,{importance:e.target.value as Choice['importance']})}><option value="preferred">Preferred</option><option value="required">Required</option></select>{c.method==='travel_time'&&<label className="small-input"><span>Maximum journey</span><select value={choices[c.id].maximumMinutes??Number(c.defaults.maximumMinutes??30)} onChange={e=>change(c.id,{maximumMinutes:Number(e.target.value)})}>{[15,30,60,90].map(m=><option key={m} value={m}>{m} min</option>)}</select></label>}{c.id==='health.hospital'&&<label className="small-input"><span>Clinical service</span><input placeholder="Optional, e.g. cardiology" value={choices[c.id].requiredService??''} onChange={e=>change(c.id,{requiredService:e.target.value})}/></label>}{c.id==='utilities.broadband'&&<label className="small-input"><span>Minimum speed</span><select value={choices[c.id].minimumDownloadMbps??100} onChange={e=>change(c.id,{minimumDownloadMbps:Number(e.target.value)})}>{[100,500,1000].map(n=><option key={n} value={n}>{n} Mbps</option>)}</select></label>}{c.method==='distance'&&<label className="small-input"><span>Desired distance</span><select value={choices[c.id].maximumDistanceM??2000} onChange={e=>change(c.id,{maximumDistanceM:Number(e.target.value)})}>{[500,1000,2000,5000].map(m=><option key={m} value={m}>{m/1000} km</option>)}</select></label>}</>}</div>)}</div></details>)}</div>;}
